# version of sintax
version: "3.9"

services:
  app: # name of service
    build:
      context: . # build inside current directory
    ports:
      - "8000:8000" # my-machine:docker-container
    volumes:
      - ./app:/app # copy and sync /app folder
    command: > # command t run the service
      sh -c "python manage.py runserver 0.0.0.0:8000"